name: Nuget Release

on:
  release:
    types: [published]

env:
  RELEASE_TYPE: ""
  PRE_RELEASE: ${{ github.event.release.prerelease }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Determine Release Time
        run: |
          if ${PRE_RELEASE}; then
            RELEASE_TYPE="beta"
            echo Doing beta release
          else
            RELEASE_TYPE = ""
          fi
