name: Nuget Release

on:
  release:
    types: [published]

env:
  PRE_RELEASE: ${{ github.event.release.prerelease }}
  MAJOR_VERSION: ${{ vars.MAJOR_VERSION }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 9.0.x
      - name: Determine Release Type
        run: |
          if ${PRE_RELEASE}; then
            echo "RELEASE_TYPE=beta" >> "$GITHUB_ENV"
            echo Doing beta release
          else
            RELEASE_TYPE=""
          fi
      - name: Set Release Version
        run: |
          git fetch origin --tags
          TAG_VERSION=$(git tag --list "${MAJOR_VERSION}.*.*" --sort=-version:refname | head -n 1)
          echo "RELEASE_VERSION=${TAG_VERSION}-${RELEASE_TYPE}" >> "$GITHUB_ENV"
      
      - name: Print Release Version
        run: |
          echo "Release / Nuget version will be: ${RELEASE_VERSION}"

      - name: Pack
        run: dotnet pack KyameruFull.sln -o ./dist -c Release -p:PackageVersion=$RELEASE_VERSION

      - name: List Packages
        run: |
          cd dist
          ls

      - name: Push
        run: dotnet nuget push ./dist/*.nupkg --api-key ${{ secrets.KYAMERU_NUGET }} -s https://api.nuget.org/v3/index.json
