name: Nuget Release

on:
  release:
    types: [published]

env:
  PRE_RELEASE: ${{ github.event.release.prerelease }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Determine Release Type
        run: |
          if ${PRE_RELEASE}; then
            echo "RELEASE_TYPE=true" >> "$GITHUB_ENV"
            echo Doing beta release
          else
            echo "RELEASE_TYPE=false" >> "$GITHUB_ENV"
          fi
      - name: Set Release Version
        run: |
          echo "RELEASE_VERSION=$(python ./.ci/getversion.py $RELEASE_TYPE 2>&1)" >> "$GITHUB_ENV"
      
      - name: Print Release Version
        run: |
          echo "Release / Nuget version will be: ${RELEASE_VERSION}"

      - name: Pack
        run: dotnet pack KyameruFull.sln -o ./dist -c Release -p:PackageVersion=$RELEASE_VERSION

      - name: List Packages
        run: |
          cd dist
          ls

      - name: Push
        run: dotnet nuget push ./dist/*.nupkg --api-key ${{ secrets.KYAMERU_NUGET }} -s https://api.nuget.org/v3/index.json
