name: Sonarcloud-Scanner

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ main ]

# need to add build...somewhere
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: 3.1.301
      - name: Install dependencies
        run: dotnet restore build/Kyameru.sln
      - name: Build
        run: dotnet build build/Kyameru.sln --configuration Release --no-restore
      - name: Test
        run: dotnet test tests/UnitTests/Kyameru.Tests/Kyameru.Tests.csproj --no-restore --verbosity normal
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args:
            -Dsonar.organization=djsuperchief
            -Dsonar.projectKey=Kyameru
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=source/
            -Dsonar.test.exclusions=tests/**
            -Dsonar.tests=tests/
            -Dsonar.verbose=true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}