name: Test pipeline steps
on:
    workflow_dispatch:

jobs:
  tag-test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - uses: actions/checkout@v3
      - name: generate_tag
        run: |
            NEW_TAG=$(python ./.ci/bump.py 2>&1)
            echo "Generated new tag: $NEW_TAG"

            git config user.name "GitHub Actions"
            git config user.email "github-actions@users.noreply.github.com"
            git tag $NEW_TAG
            git push origin $NEW_TAG
